version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: mkdir shared-coverage
      - persist_to_workspace:
          root: ~/project
          paths: shared-coverage
  test1:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: g++ --coverage test1.cpp && ./a.out
      - run: mv *.gcda shared-coverage && mv *.gcno shared-coverage
      - persist_to_workspace:
          root: ~/project
          paths: shared-coverage
  test2:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: g++ --coverage test2.cpp && ./a.out
      - run: mv *.gcda shared-coverage && mv *.gcno shared-coverage
      - persist_to_workspace:
          root: ~/project
          paths: shared-coverage
  test3:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: g++ --coverage test3.cpp && ./a.out
      - run: mv *.gcda shared-coverage && mv *.gcno shared-coverage
      - persist_to_workspace:
          root: ~/project
          paths: shared-coverage
  gather:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
#      - run: curl -fLO https://sourceforge.net/projects/ltp/files/Coverage%20Analysis/LCOV-1.12/lcov-1.12.tar.gz || curl -fLO https://downloads.sourceforge.net/project/ltp/Coverage%20Analysis/LCOV-1.12/lcov-1.12.tar.gz || wget http://sourceforge.mirrorservice.org/l/project/lt/ltp/Coverage%20Analysis/LCOV-1.12/lcov-1.12.tar.gz || wget -O lcov-1.12.tar.gz http://launchpad.net/ubuntu/+archive/primary/+files/lcov_1.12.orig.tar.gz
#      - run: tar xvzf lcov-1.12.tar.gz
#      - run: cd lcov-1.12 && sudo make install
      - run: sudo apt-get install lcov

      - attach_workspace:
          at: ~/project
      - run: ls -lah shared-coverage
      - run: lcov --gcov-tool=gcov --directory shared-coverage --base-directory . --capture --output-file shared-coverage/coverage.info
#      - run: lcov --gcov-tool=gcov --rc lcov_branch_coverage=1 --directory shared-coverage --base-directory . --capture --output-file shared-coverage/coverage.info
#      - run: lcov --gcov-tool=gcov --rc lcov_branch_coverage=1 --remove shared-coverage/coverage.info "/usr*" "*/libs/geometry/*" -o shared-coverage/coverage.info

#Coveralls
      - run: gem install coveralls-lcov
      - run: sudo apt-get install jq
      - run: coveralls-lcov --repo-token=$COVERALLS_REPO_TOKEN -v -n shared-coverage/coverage.info > shared-coverage/coverage.json
# not possible with workspaces
# | .service_number = \"$CIRCLE_BUILD_NUM\"
      - run: jq -c ".service_name = \"circle-ci\" | .git .branch =\"$CIRCLE_BRANCH\"" shared-coverage/coverage.json > shared-coverage/processed.json
      - run: ls -lah shared-coverage
      - run: curl --retry 3 -F "json_file=@shared-coverage/processed.json" 'https://coveralls.io/api/v1/jobs'

#Codecov
      - run: curl -s https://codecov.io/bash > .codecov
      - run: chmod +x .codecov
      - run: ./.codecov -t $CODECOV_TOKEN -f shared-coverage/coverage.info -x gcov

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
      - test1:
          requires:
            - test
      - test2:
          requires:
            - test
      - test3:
          requires:
            - test
      - gather:
          requires:
            - test1
            - test2
            - test3
